apiVersion: v2
name: kubeoptix-analyzer
description: Helm chart to deploy kubeoptix-analyzer API on OpenShift
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.26.0-0"
keywords:
  - openshift
  - kubernetes
  - analyzer
  - kubeoptix
maintainers:
  - name: ShiftWise AI
