deploy:
  enabled: true

namespace:
  create: false
  name: shiftwise-ai

image:
  useBuildOutput: true
  repository: quay.io/parraes/kubeoptix-analyzer
  tag: 1.0.0
  pullPolicy: Always

build:
  enabled: true
  registryHost: image-registry.openshift-image-registry.svc:5000
  imageStreamName: kubeoptix-analyzer
  outputTag: 1.0.0
  containerfilePath: Containerfile
  git:
    uri: https://github.com/ShiftWise-AI/kubeoptix-analyzer.git
    ref: main
    sourceSecret: github-auth

nameOverride: ""
fullnameOverride: ""

startup:
  loginWithServiceAccount: false
  script: ""

podEnv:
  HOME: /tmp
  KUBECONFIG: /tmp/kubeconfig

systemSettings:
  # kubeoptix-configurations service (GET /system-settings)
  url: "http://configurations-api:8000"

env:
  TZ: UTC
  LLM_BASE_URL: https://api.openai.com/v1

service:
  api:
    enabled: true
    name: analyzer-api
    type: ClusterIP
    port: 8000
    targetPort: 8000

scalePolicy:
  enabled: true
  maxReplicas: 1

persistence:
  enabled: true
  existingClaim: harvester-app-data
  mountPath: /app/data


resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
