{{- if .Values.build.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "kubeoptix-analyzer.fullname" . }}
  namespace: {{ include "kubeoptix-analyzer.namespace" . }}
  labels:
    {{- include "kubeoptix-analyzer.labels" . | nindent 4 }}
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.build.git.uri | quote }}
      ref: {{ .Values.build.git.ref | quote }}
    {{- if .Values.build.git.sourceSecret }}
    sourceSecret:
      name: {{ .Values.build.git.sourceSecret | quote }}
    {{- end }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.build.containerfilePath | quote }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ printf "%s:%s" .Values.build.imageStreamName .Values.build.outputTag | quote }}
{{- end }}
