{{- if .Values.buildConfig.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "kubeoptix-analyzer.fullname" . }}
  labels:
    {{- include "kubeoptix-analyzer.labels" . | nindent 4 }}
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.buildConfig.git.uri | quote }}
      ref: {{ .Values.buildConfig.git.ref | quote }}
    {{- if .Values.buildConfig.git.contextDir }}
    contextDir: {{ .Values.buildConfig.git.contextDir | quote }}
    {{- end }}
    sourceSecret:
      name: {{ .Values.buildConfig.sourceSecretName | quote }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.buildConfig.dockerfilePath | quote }}
  output:
    to:
      kind: ImageStreamTag
      name: "{{ default (include "kubeoptix-analyzer.fullname" .) .Values.buildConfig.output.imageStreamName }}:{{ default "latest" .Values.buildConfig.output.tag }}"
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  triggers:
    {{- if .Values.buildConfig.triggers.configChange }}
    - type: ConfigChange
    {{- end }}
{{- end }}
