{{- if .Values.buildConfig.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ default (include "kubeoptix-analyzer.fullname" .) .Values.buildConfig.output.imageStreamName }}
  labels:
    {{- include "kubeoptix-analyzer.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true
{{- end }}
